
{
    "name": "Simple Module",
    "version": "16.0.1.0.0",
    "summary": "A simple Odoo module with a basic view.",
    "author": "Generated by ChatGPT",
    "category": "Tools",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "views/simple_model_views.xml"
    ],
    "installable": True,
    "application": False,
    "auto_install": False
}
